module.exports=[
    {
        "_id":1001,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.4 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','S','L','XL'],
        "price":2799,
        "color":["Blue","Green"],
        "image":["https://i.ibb.co/BrkP57y/m1.png","https://i.ibb.co/X2BS8Cb/m1c.png"],
        "discount":22,
        "quantity":4,
        "shippingCharges":49
    },
    {
        "_id":1002,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.5 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/QJVdNQF/m2.png","https://i.ibb.co/7b3B9ry/m2c.png"],
        "discount":12,
        "quantity":10,
        "shippingCharges":99
    },
    {
        "_id":1003,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":3.7 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','S','M','L'],
        "price":2199,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/1Ls6HKJ/m3.png","https://i.ibb.co/k4J7zxV/m3c.png"],
        "discount":18,
        "quantity":6,
        "shippingCharges":49
    },
   
    {
        "_id":1004,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.1 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['S','M','L','XL'],
        "price":3999,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/HGLjJtB/m4.png","https://i.ibb.co/r7JwHjK/m4c.png",],
        "discount":20,
        "quantity":12,
        "shippingCharges":49
    },
    {
        "_id":1005,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":3.9 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','M','L','XL'],
        "price":3599,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/hH1PqPr/m5.png","https://i.ibb.co/YW2QcZ5/m5c.png",],
        "discount":15,
        "quantity":1,
        "shippingCharges":99
    },
    {
        "_id":1006,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":5.0 ,
        "idealFor":"men",
        "category":"Sports",
        "size":['XS','S','XL'],
        "price":4999,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/zX08ggz/m6.png","https://i.ibb.co/25tfcmd/m6c.png",],
        "discount":25,
        "quantity":3,
        "shippingCharges":49
    },
   
    {
        "_id":1007,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.2 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['M','L','XL'],
        "price":2499,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/yNzFFB0/m7.png","https://i.ibb.co/DMYRBgj/m7c.png",],
        "discount":20,
        "quantity":15,
        "shippingCharges":49
    },
    {
        "_id":1008,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.5 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['XS','S','L'],
        "price":3099,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/c6p471z/m8.png","https://i.ibb.co/fQp7btJ/m8c.png",],
        "discount":10,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1009,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.7 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['XS','M','XL'],
        "price":3799,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/QvvQp0S/m9.png","https://i.ibb.co/hcd9v4P/m9c.png",],
        "discount":12,
        "quantity":55,
        "shippingCharges":49
    },
   
    {
        "_id":1010,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":3.2 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['S','M','L'],
        "price":3399,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/HzfVGBc/m10.png","https://i.ibb.co/LhksmKT/m10c.png",],
        "discount":30,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1011,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.1 ,
        "idealFor":"men",
        "category":"Casual",
        "size":['XS','M','L','XL'],
        "price":2599,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/WKMbt9X/m11.png","https://i.ibb.co/5TB5C3R/m11c.png",],
        "discount":18,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1012,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.7 ,
        "idealFor":"men",
        "category":"Formal",
        "size":['XS','S','M','XL'],
        "price":2799,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/YBk6jkZ/m12.png","https://i.ibb.co/W3QVMkW/m12c.png"],
        "discount":24,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1013,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.0 ,
        "idealFor":"men",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":3299,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/XkRVYc8/m13.png","https://i.ibb.co/sjFnfqv/m13c.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1014,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.5 ,
        "idealFor":"men",
        "category":"Formal",
        "size":['XS','S','M','L'],
        "price":3499,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/FWKT7gs/m14.png","https://i.ibb.co/HC7w1MB/m14c.png",],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1015,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for men",
        "rating":4.3 ,
        "idealFor":"men",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":2399,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/4t1p9Rh/m15.png","https://i.ibb.co/R79hFVN/m15c.png"],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1016,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.4 ,
        "idealFor":"women",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":3999,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/HTb9pHV/w1.png","https://i.ibb.co/wNVD0jJ/w1c.png"],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1017,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.5 ,
        "idealFor":"women",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/2sVFNgp/w2.png","https://i.ibb.co/Yj6mZCc/w2c.png"],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1018,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.7 ,
        "idealFor":"women",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":2899,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/7G2kPDk/w3.png","https://i.ibb.co/chHqRVL/w3c.png",],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1019,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.4 ,
        "idealFor":"women",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":2599,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/PjLBMgK/w4.png","https://i.ibb.co/zhSf1rm/w4c.png",],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1020,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.5 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":3299,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/729Q0HZ/w5.png","https://i.ibb.co/2S1d3Wm/w5c.png",],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1021,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.7 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":3499,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/r6QmZdg/w6.png","https://i.ibb.co/hBz3wZr/w6c.png"],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1022,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.4 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":1999,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/FXkpy0r/w7.png","https://i.ibb.co/FVksj2N/w7c.png",],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1023,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.5 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":1899,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/PYQwn2q/w8.png","https://i.ibb.co/hfnvmBL/w8c.png",],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1024,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for women",
        "rating":4.7 ,
        "idealFor":"women",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":2199,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/kq6Knk5/w9.png","https://i.ibb.co/fYFBdxy/w9c.png",],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1025,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.4 ,
        "idealFor":"kids",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":2999,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/p2VQMkT/k1.png","https://i.ibb.co/gvrm5T5/k1c.png",],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1026,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.5 ,
        "idealFor":"kids",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":2099,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/fr32VJZ/k2.png","https://i.ibb.co/6BF4FX6/k2c.png",],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1027,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.7 ,
        "idealFor":"kids",
        "category":"Formal",
        "size":['XS','S','M','L','XL'],
        "price":3199,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/DpJHPhw/k3.png","https://i.ibb.co/LxbcwdB/k3c.png",],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1028,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.4 ,
        "idealFor":"kids",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":2199,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/vqQG7Pf/k4.png","https://i.ibb.co/rZWnzXn/k4c.png",],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
    {
        "_id":1029,
        "name":"Nike Air Light 2002",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.5 ,
        "idealFor":"kids",
        "category":"Casual",
        "size":['XS','S','M','L','XL'],
        "price":1849,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/HTpwRY4/k5.png","https://i.ibb.co/D1Xx3Mb/k5c.png",],
        "discount":15,
        "quantity":50,
        "shippingCharges":99
    },
    {
        "_id":1030,
        "name":"Nike Light Max 2001",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.7 ,
        "idealFor":"kids",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":2499,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/rdgq6DC/k6.png","https://i.ibb.co/HXX9wDy/k6c.png",],
        "discount":20,
        "quantity":55,
        "shippingCharges":49
    },
    {
        "_id":1031,
        "name":"Nike Air Max 2020",
        "description":"A lightweight and comfortable shoes for kids",
        "rating":4.4 ,
        "idealFor":"kids",
        "category":"Sports",
        "size":['XS','S','M','L','XL'],
        "price":2249,
        "color":["Red","Blue","Green"],
        "image":["https://i.ibb.co/7gJG8Zj/k7.png","https://i.ibb.co/51Bytdy/k7c.png",],
        "discount":20,
        "quantity":90,
        "shippingCharges":49
    },
]
